# Generated by Django 6.0.3 on 2026-04-07 19:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatComorbilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True)),
                ('definicion_tecnica', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CatDiagnostico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=100, unique=True)),
                ('nombre_diagnostico', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ArchivoFuente',
            fields=[
                ('id_archivo', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre_archivo', models.CharField(max_length=255)),
                ('tipo_documento', models.CharField(max_length=20)),
                ('ruta_almacenamiento', models.TextField()),
                ('admision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos', to='patients.admision')),
            ],
        ),
        migrations.CreateModel(
            name='DiagnosticoEpisodio',
            fields=[
                ('id_diagnostico_ep', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('es_inferido', models.BooleanField(default=False)),
                ('confianza_ia', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('auditado_por_medico', models.BooleanField(default=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('admision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnosticos_inferidos', to='patients.admision')),
                ('catalogo_dx', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='clinical.catdiagnostico')),
            ],
        ),
        migrations.CreateModel(
            name='MedicamentoAdmision',
            fields=[
                ('id_medicacion', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('dosis_valor', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('dosis_unidad', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha_hora_inicio', models.DateTimeField(blank=True, null=True)),
                ('coordenadas_zoom', models.JSONField(blank=True, null=True)),
                ('admision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicamentos', to='patients.admision')),
                ('archivo_fuente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clinical.archivofuente')),
            ],
        ),
        migrations.CreateModel(
            name='ObservacionBiomedica',
            fields=[
                ('id_observacion', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('parametro', models.CharField(max_length=100)),
                ('valor_numerico', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('unidad_medida', models.CharField(blank=True, max_length=20, null=True)),
                ('rango_referencia_min', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('rango_referencia_max', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('fecha_hora_registro', models.DateTimeField()),
                ('coordenadas_zoom', models.JSONField(blank=True, null=True)),
                ('es_diario', models.BooleanField(default=False)),
                ('admision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observaciones', to='patients.admision')),
                ('archivo_fuente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clinical.archivofuente')),
            ],
        ),
        migrations.CreateModel(
            name='ComorbilidadAdmision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presente', models.BooleanField(default=True)),
                ('descripcion_original', models.TextField(blank=True, null=True)),
                ('coordenadas_zoom', models.JSONField(blank=True, null=True)),
                ('admision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comorbilidades_detectadas', to='patients.admision')),
                ('archivo_fuente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clinical.archivofuente')),
                ('comorbilidad', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='clinical.catcomorbilidad')),
            ],
            options={
                'unique_together': {('admision', 'comorbilidad')},
            },
        ),
    ]
