# Generated by Django 6.0.3 on 2026-05-18 15:30

import apps.clinical.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivofuente',
            name='archivo_fisico',
            field=models.FileField(blank=True, null=True, upload_to=apps.clinical.models.ruta_dinamica_inaaqc),
        ),
    ]
