# Generated by Django 6.0.3 on 2026-06-02 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0002_alter_archivofuente_archivo_fisico'),
        ('patients', '0003_admision_esta_activo'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatSoporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True)),
                ('categoria', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PuntajesEpisodio',
            fields=[
                ('admision', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='patients.admision')),
                ('sofa_respiratorio', models.IntegerField(default=0)),
                ('sofa_cardiovascular', models.IntegerField(default=0)),
                ('sofa_renal', models.IntegerField(default=0)),
                ('sofa_hepatico', models.IntegerField(default=0)),
                ('sofa_coagulacion', models.IntegerField(default=0)),
                ('sofa_neurologico', models.IntegerField(default=0)),
                ('sofa_total', models.IntegerField(default=0)),
                ('saps3_puntos', models.IntegerField(default=0)),
                ('saps3_mortalidad_estimada', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
                ('datos_insuficientes', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SoporteAdmision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora_inicio', models.DateTimeField(blank=True, null=True)),
                ('fecha_hora_fin', models.DateTimeField(blank=True, null=True)),
                ('en_primeras_24h', models.BooleanField(default=True)),
                ('admision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.admision')),
                ('soporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinical.catsoporte')),
            ],
            options={
                'unique_together': {('admision', 'soporte')},
            },
        ),
    ]
