# Generated by Django 6.0.3 on 2026-06-02 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0003_catsoporte_puntajesepisodio_soporteadmision'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catcomorbilidad',
            options={'verbose_name_plural': 'Catálogo de Comorbilidades'},
        ),
        migrations.AddField(
            model_name='catcomorbilidad',
            name='categoria',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
