# Generated by Django 6.0.3 on 2026-06-03 16:02

import apps.clinical.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0004_alter_catcomorbilidad_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivofuente',
            name='archivo_fisico',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to=apps.clinical.models.ruta_dinamica_inaaqc),
        ),
    ]
