# Generated by Django 6.0.3 on 2026-06-03 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0005_alter_archivofuente_archivo_fisico'),
    ]

    operations = [
        migrations.AddField(
            model_name='catcomorbilidad',
            name='palabras_clave',
            field=models.TextField(blank=True, help_text='Sinónimos separados por comas', null=True),
        ),
        migrations.AddField(
            model_name='catdiagnostico',
            name='palabras_clave',
            field=models.TextField(blank=True, help_text='Sinónimos en francés separados por comas', null=True),
        ),
        migrations.AddField(
            model_name='catsoporte',
            name='palabras_clave',
            field=models.TextField(blank=True, help_text='Sinónimos separados por comas', null=True),
        ),
    ]
