# Generated by Django 6.0.3 on 2026-04-07 19:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id_paciente', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dossier_erasme', models.CharField(max_length=20, unique=True)),
                ('dossier_mpi', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('nombres', models.CharField(max_length=255)),
                ('apellidos', models.CharField(max_length=255)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('sexo', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('U', 'Desconocido')], max_length=1, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Admision',
            fields=[
                ('id_admision', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero_episodio', models.CharField(max_length=9, unique=True)),
                ('fecha_ingreso', models.DateTimeField()),
                ('fecha_salida', models.DateTimeField(blank=True, null=True)),
                ('cama_sala', models.CharField(blank=True, max_length=50, null=True)),
                ('peso_ingreso_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('talla_ingreso_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admisiones', to='patients.paciente')),
            ],
            options={
                'indexes': [models.Index(fields=['fecha_ingreso', 'fecha_salida'], name='patients_ad_fecha_i_f35f00_idx')],
            },
        ),
    ]
