# Generated by Django 6.0.3 on 2026-04-20 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='esta_activo',
            field=models.BooleanField(default=True),
        ),
    ]
