# Generated by Django 6.0.3 on 2026-04-20 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_paciente_esta_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='admision',
            name='esta_activo',
            field=models.BooleanField(default=True),
        ),
    ]
